name: "Kpt Live - KinD Tests"
on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: 'Kubernetes Version to Test'
        required: true
        default: '1.18'
  push:
    branches:
      - master
      - next
      - e2eTesting
  pull_request:
    branches:
      - master
      - next

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Pinned to Commit to ensure action is consistent: https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
      # If you upgrade this version confirm the changes match your expectations
      - name: Install KinD
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          version: "v0.9.0"
          skipClusterCreation: true
      - name: Run Tests
        run: |
          ./e2e/live/end-to-end-test.sh -k ${{ github.event.inputs.k8s_version }}
